version: '3.8'

services:
  zammad-nginx:
    image: ${IMAGE_REPO:-ghcr.io/zammad/zammad}:${VERSION:-6.3.1-185}
    environment:
      MEMCACHE_SERVERS: ${MEMCACHE_SERVERS:-zammad-memcached:11211}
      POSTGRESQL_DB: ${POSTGRES_DB:-zammad_production}
      POSTGRESQL_HOST: ${POSTGRES_HOST:-zammad-postgresql}
      POSTGRESQL_USER: ${POSTGRES_USER:-zammad}
      POSTGRESQL_PASS: ${POSTGRES_PASS:-zammad}
      POSTGRESQL_PORT: ${POSTGRES_PORT:-5432}
      REDIS_URL: ${REDIS_URL:-redis://zammad-redis:6379}
      NGINX_PORT: ${NGINX_PORT:-8080}
      NGINX_SERVER_NAME: helpdesk.spx.shippex.net
      NGINX_SERVER_SCHEME: https
    volumes:
      - zammad-storage:/opt/zammad/storage
    depends_on:
      - zammad-memcached
      - zammad-postgresql
      - zammad-redis
      - zammad-railsserver
    ports:
      - "${NGINX_EXPOSE_PORT:-443}:${NGINX_PORT:-8080}"
    container_name: helpdesk-${RANDOM_STRING}  # Replace ${RANDOM_STRING} with a random string generator
    restart: always
    labels:
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 8080}}'
      - 'caddy_0.handle_path=/*'
      - 'caddy_0=https://helpdesk.spx.shippex.net'
      - caddy_0.header=-Server

volumes:
  zammad-storage:
    name: zammad-storage-${RANDOM_STRING}  # Replace ${RANDOM_STRING} with a random string generator

networks:
  default:
    external:
      name: zammad-network
